// 18 combinatorics challenges (Member 3). `answer` is always a number computed with mathUtils.
import { fact, nPr, nCr, multiset, starsAndBars, unionDivisible } from "./mathUtils.js";

export const TOPICS = { COUNT: "Basic counting", PERM: "Permutations", COMB: "Combinations", PHP: "Pigeonhole", IE: "Inclusion-Exclusion" };
const T = TOPICS;
const M = { fact, nPr, nCr, multiset, starsAndBars, unionDivisible };

export const combinatoricsQuestions = [
  // ---- Easy ----
  { id: 'c01', topic: T.COUNT, difficulty: 'easy', answer: 3 * 4 * 2,
    text: 'A shop sells 3 shirts, 4 pairs of trousers and 2 hats. How many different outfits (one of each) can you make?',
    hint: 'Multiplication rule: multiply the choices at each step.',
    explanation: '3 × 4 × 2 = 24.' },
  { id: 'c02', topic: T.COUNT, difficulty: 'easy', answer: 10 ** 4,
    text: 'A PIN has 4 digits (0–9) and digits may repeat. How many PINs are possible?',
    hint: 'Each of the 4 positions has the same number of choices.',
    explanation: '10 × 10 × 10 × 10 = 10 000.' },
  { id: 'c03', topic: T.PERM, difficulty: 'easy', answer: M.fact(5),
    text: 'In how many ways can 5 different books be arranged on a shelf?',
    hint: 'Order matters and every book is used: n!',
    explanation: '5! = 120.' },
  { id: 'c04', topic: T.PERM, difficulty: 'easy', answer: M.nPr(6, 3),
    text: 'How many 3-letter codes can be made from the letters A–F if no letter is repeated?',
    hint: 'Order matters, choose 3 of 6: P(6,3).',
    explanation: 'P(6,3) = 6 × 5 × 4 = 120.' },
  { id: 'c05', topic: T.COMB, difficulty: 'easy', answer: M.nCr(8, 3),
    text: 'A teacher picks 3 students from a group of 8 to form a team. How many different teams are possible?',
    hint: 'Order does not matter: C(n, r).',
    explanation: 'C(8,3) = 8! / (3! · 5!) = 56.' },
  { id: 'c06', topic: T.PHP, difficulty: 'easy', answer: 12 + 1,
    text: 'What is the smallest number of people that guarantees at least two of them were born in the same month?',
    hint: 'There are 12 "boxes" (months). Think worst case.',
    explanation: '12 people can all differ, so the 13th must repeat a month: 13.' },

  // ---- Medium ----
  { id: 'c07', topic: T.COUNT, difficulty: 'medium', answer: 26 ** 2 * 10 ** 3,
    text: 'A licence plate has 2 letters (A–Z) followed by 3 digits (0–9). Repeats are allowed. How many plates exist?',
    hint: 'Five independent positions.',
    explanation: '26² × 10³ = 676 × 1000 = 676 000.' },
  { id: 'c08', topic: T.PERM, difficulty: 'medium', answer: M.multiset(5, 2, 2),
    text: 'How many distinct arrangements of the letters of the word LEVEL are there?',
    hint: 'L appears twice and E appears twice: divide by the repeats.',
    explanation: '5! / (2! · 2!) = 30.' },
  { id: 'c09', topic: T.PERM, difficulty: 'medium', answer: M.fact(6),
    text: 'In how many ways can 7 people sit around a circular table? (Rotations count as the same seating.)',
    hint: 'Fix one person, arrange the rest: (n − 1)!',
    explanation: '(7 − 1)! = 720.' },
  { id: 'c10', topic: T.COMB, difficulty: 'medium', answer: M.nCr(6, 2) * M.nCr(5, 2),
    text: 'A committee of 4 is chosen from 6 men and 5 women with exactly 2 women. How many committees are possible?',
    hint: 'Choose the men and the women separately, then multiply.',
    explanation: 'C(5,2) × C(6,2) = 10 × 15 = 150.' },
  { id: 'c11', topic: T.PHP, difficulty: 'medium', answer: 5 + 1,
    text: 'A drawer holds socks in 5 colours. What is the minimum number of socks you must take (without looking) to be sure of a matching pair?',
    hint: 'Worst case: you draw one of each colour first.',
    explanation: '5 socks can all differ; the 6th must match: 6.' },
  { id: 'c12', topic: T.IE, difficulty: 'medium', answer: 60 + 45 - 20,
    text: 'Of 100 students, 60 study Maths, 45 study Physics and 20 study both. How many study at least one of the two?',
    hint: '|A ∪ B| = |A| + |B| − |A ∩ B|.',
    explanation: '60 + 45 − 20 = 85.' },

  // ---- Hard ----
  { id: 'c13', topic: T.PERM, difficulty: 'hard', answer: M.multiset(11, 4, 4, 2),
    text: 'How many distinct arrangements of the letters of MISSISSIPPI are there?',
    hint: 'I ×4, S ×4, P ×2, M ×1 — divide by each repeat.',
    explanation: '11! / (4! · 4! · 2!) = 34 650.' },
  { id: 'c14', topic: T.COMB, difficulty: 'hard', answer: M.starsAndBars(10, 4),
    text: 'In how many ways can 10 identical candies be given to 4 children (a child may get none)?',
    hint: 'Stars and bars: 10 stars and 3 bars.',
    explanation: 'C(10 + 3, 3) = C(13,3) = 286.' },
  { id: 'c15', topic: T.COMB, difficulty: 'hard', answer: M.nCr(9, 4),
    text: 'A robot walks from the bottom-left to the top-right of a grid, moving only right (5 steps) or up (4 steps). How many different paths exist?',
    hint: 'A path is a sequence of 9 moves; choose which 4 are "up".',
    explanation: 'C(9,4) = 126.' },
  { id: 'c16', topic: T.PHP, difficulty: 'hard', answer: 10 + 1,
    text: 'How many numbers must you pick from 1, 2, …, 20 to guarantee that two of them add up to 21?',
    hint: 'Pair the numbers: (1,20), (2,19), …',
    explanation: 'There are 10 pairs summing to 21. Picking 10 numbers can take one from each pair, so 11 are needed.' },
  { id: 'c17', topic: T.IE, difficulty: 'hard', answer: M.unionDivisible(100, [2, 3, 5]),
    text: 'How many integers from 1 to 100 are divisible by 2, 3 or 5?',
    hint: 'Add singles, subtract pairs (lcm 6, 10, 15), add the triple (lcm 30).',
    explanation: '(50 + 33 + 20) − (16 + 10 + 6) + 3 = 74.' },
  { id: 'c18', topic: T.IE, difficulty: 'hard', answer: 1000 - M.unionDivisible(1000, [3, 5, 7]),
    text: 'How many integers from 1 to 1000 are divisible by none of 3, 5 and 7?',
    hint: 'Count the numbers divisible by at least one, then subtract from 1000.',
    explanation: 'Divisible by at least one: (333+200+142) − (66+47+28) + 9 = 543, so 1000 − 543 = 457.' }
];
