// Hasse Diagram Builder questions. "hasse" questions are built in React Flow; "choice" questions may show a poset.
const D = (...elements) => ({ order: "divides", elements });

export const hasseQuestions = [
  // ---- Easy ----
  { id: "h01", type: "hasse", difficulty: "easy", topic: "Hasse diagrams", poset: D(1, 2, 3, 6),
    text: "Build the Hasse diagram of the divisors of 6 ordered by divisibility (a ≤ b when a divides b).",
    hint: "Connect 1 to the primes, and each prime to 6.",
    explanation: "Covers: 1–2, 1–3, 2–6, 3–6. There is no 1–6 edge because 2 and 3 lie between." },
  { id: "h02", type: "choice", difficulty: "easy", topic: "Cover relations",
    text: "How many edges does the Hasse diagram of ({1, 2, 3, 4, 6, 12}, |) have?",
    options: ["5", "6", "7", "9"], answer: 2,
    hint: "List the pairs where one divides the other with nothing strictly between them.",
    explanation: "Covers: 1–2, 1–3, 2–4, 2–6, 3–6, 4–12, 6–12. That is 7 edges." },
  { id: "h03", type: "choice", difficulty: "easy", topic: "Extremal elements", poset: D(2, 3, 4, 6, 12),
    text: "Which elements of ({2, 3, 4, 6, 12}, |) are minimal?",
    options: ["2 and 3", "Only 2", "Only 12", "2, 3 and 4"], answer: 0,
    hint: "A minimal element has nothing below it.",
    explanation: "Neither 2 nor 3 has a smaller element in the set, so both are minimal. 4 sits above 2." },
  { id: "h04", type: "choice", difficulty: "easy", topic: "Partial orders",
    text: "Which property is NOT required of a partial order?",
    options: ["Reflexive", "Antisymmetric", "Transitive", "Symmetric"], answer: 3,
    hint: "A partial order is reflexive, antisymmetric and transitive.",
    explanation: "A partial order is reflexive, antisymmetric and transitive. It is almost never symmetric." },
  { id: "h05", type: "hasse", difficulty: "easy", topic: "Hasse diagrams",
    poset: { order: "pairs", elements: ["a", "b", "c", "d"], pairs: [["a", "b"], ["a", "c"], ["b", "d"], ["c", "d"]] },
    text: "Build the Hasse diagram of the poset on {a, b, c, d} with a ≤ b, a ≤ c, b ≤ d and c ≤ d (plus whatever follows by reflexivity and transitivity).",
    hint: "a ≤ d follows from transitivity, so it needs no edge of its own.",
    explanation: "Covers: a–b, a–c, b–d, c–d: a diamond. The pair a–d is implied through b (or c)." },
  { id: "h06", type: "choice", difficulty: "easy", topic: "Extremal elements", poset: D(1, 2, 3, 4, 6, 12),
    text: "Which element is the greatest element of ({1, 2, 3, 4, 6, 12}, |)?",
    options: ["1", "6", "12", "There is none"], answer: 2,
    hint: "The greatest element is divisible by every other element.",
    explanation: "Every element divides 12, so 12 is the greatest element." },

  // ---- Medium ----
  { id: "h07", type: "hasse", difficulty: "medium", topic: "Hasse diagrams", poset: D(1, 2, 3, 4, 6, 12),
    text: "Build the Hasse diagram of the divisors of 12 ordered by divisibility.",
    hint: "There are 7 edges. 4 and 6 are incomparable.",
    explanation: "Covers: 1–2, 1–3, 2–4, 2–6, 3–6, 4–12, 6–12." },
  { id: "h08", type: "hasse", difficulty: "medium", topic: "Hasse diagrams",
    poset: { order: "subset", elements: [[], ["a"], ["b"], ["a", "b"]] },
    text: "Build the Hasse diagram of the subsets of {a, b} ordered by inclusion (⊆).",
    hint: "Each edge adds exactly one element to a set.",
    explanation: "Covers: ∅–{a}, ∅–{b}, {a}–{a,b}, {b}–{a,b}: a diamond again." },
  { id: "h09", type: "choice", difficulty: "medium", topic: "Comparability", poset: D(1, 2, 3, 4, 6, 12),
    text: "In ({1, 2, 3, 4, 6, 12}, |), which pair of elements is incomparable?",
    options: ["2 and 4", "3 and 12", "4 and 6", "1 and 6"], answer: 2,
    hint: "Incomparable means neither divides the other.",
    explanation: "4 does not divide 6 and 6 does not divide 4. The other pairs are each related by divisibility." },
  { id: "h10", type: "choice", difficulty: "medium", topic: "Cover relations", poset: D(1, 2, 3, 4, 6, 12),
    text: "Which of these elements covers 2 in ({1, 2, 3, 4, 6, 12}, |)?",
    options: ["3", "4", "12", "1"], answer: 1,
    hint: "A cover must be a multiple of 2 with nothing strictly between.",
    explanation: "4 covers 2 (so does 6, but it is not listed). 12 does not, since 4 lies between 2 and 12." },

  // ---- Hard ----
  { id: "h11", type: "hasse", difficulty: "hard", topic: "Hasse diagrams", poset: D(1, 2, 3, 5, 6, 10, 15, 30),
    text: "Build the Hasse diagram of the divisors of 30 ordered by divisibility.",
    hint: "The result is a cube: 12 edges, each multiplying by one prime.",
    explanation: "Each cover multiplies by a single prime: 1–2, 1–3, 1–5, 2–6, 2–10, 3–6, 3–15, 5–10, 5–15, 6–30, 10–30, 15–30." },
  { id: "h12", type: "hasse", difficulty: "hard", topic: "Hasse diagrams", poset: D(1, 2, 3, 4, 6, 9, 12, 18, 36),
    text: "Build the Hasse diagram of the divisors of 36 ordered by divisibility.",
    hint: "36 = 2² · 3², so the diagram is a 3 × 3 grid.",
    explanation: "Covers: 1–2, 1–3, 2–4, 2–6, 3–6, 3–9, 4–12, 6–12, 6–18, 9–18, 12–36, 18–36." },
  { id: "h13", type: "choice", difficulty: "hard", topic: "Chains", poset: D(1, 2, 3, 5, 6, 10, 15, 30),
    text: "How many elements are in a longest chain of the divisors of 30 under divisibility?",
    options: ["3", "4", "5", "8"], answer: 1,
    hint: "Walk from the bottom to the top following edges.",
    explanation: "A longest chain is 1 | 2 | 6 | 30 (or similar): 4 elements." },
  { id: "h14", type: "choice", difficulty: "hard", topic: "Antichains", poset: D(1, 2, 3, 5, 6, 10, 15, 30),
    text: "What is the size of a largest antichain in the divisors of 30 under divisibility?",
    options: ["2", "3", "4", "6"], answer: 1,
    hint: "An antichain has no two comparable elements. Try the primes.",
    explanation: "{2, 3, 5} and {6, 10, 15} are antichains of size 3, and no antichain has 4 elements." }
];
